### ISSUE TITLE
blog_code_handler_api_artists.erl:18: syntax error 

### ISSUE THREAD

**Issue by Darkhelmet0** [truqu/real-world-elm#2]
Im getting a syntax error when I run npm install && make deps app rel elm
`make[1]: Entering directory`/home/ubuntu/workspace/deps/sync'
 APP    sync.app.src
make[1]: Leaving directory `/home/ubuntu/workspace/deps/sync'
 ERLC   blog_code.erl blog_code_app.erl blog_code_config.erl blog_code_handler_api_artists.erl blog_code_handler_elm.erl blog_code_sup.erl
src/blog_code_handler_api_artists.erl:18: syntax error before: '{'
src/blog_code_handler_api_artists.erl:25: syntax error before: '{'
src/blog_code_handler_api_artists.erl:7: function allowed_methods/2 undefined
src/blog_code_handler_api_artists.erl:8: function to_json/2 undefined
src/blog_code_handler_api_artists.erl:14: variable 'Req' is unused
make: *** [ebin/blog_code.app] Error 1`

**Comment by ghost** [comment]
Thanks for reporting this. Two questions:
1. What version of erlang do you have installed?
2. What happens if you just run `make`?

**Comment by Darkhelmet0** [comment]
1. erlang version:  "R16B02_basho8"
2. I get the same error:

```
`make[1]: Leaving directory `/home/ubuntu/workspace/deps/sync'
 ERLC   blog_code.erl blog_code_app.erl blog_code_config.erl blog_code_handler_api_artists.erl blog_code_handler_elm.erl blog_code_sup.erl
src/blog_code_handler_api_artists.erl:18: syntax error before: '{'
src/blog_code_handler_api_artists.erl:25: syntax error before: '{'
src/blog_code_handler_api_artists.erl:7: function allowed_methods/2 undefined
src/blog_code_handler_api_artists.erl:8: function to_json/2 undefined
make[1]: *** [ebin/blog_code.app] Error 1
make: *** [all] Error 2`
```

**Comment by ghost** [comment]
You need version 18 of Erlang.

**Comment by ghost** [comment]
Closing this issue for now, please let me know if you need more help.
